alter table "public"."events" alter column "end_time" set data type timestamp with time zone using "end_time"::timestamp with time zone;

alter table "public"."events" alter column "start_time" set data type timestamp with time zone using "start_time"::timestamp with time zone;

alter table "public"."tournaments" alter column "end_time" set data type timestamp with time zone using "end_time"::timestamp with time zone;

alter table "public"."tournaments" alter column "start_time" set data type timestamp with time zone using "start_time"::timestamp with time zone;

alter table "public"."tournaments" drop column "description";

alter table "public"."tournaments" alter column "id" drop default;

alter table "public"."tournaments" alter column "id" add generated by default as identity;

alter table "public"."tournaments" alter column "id" set data type bigint using "id"::bigint;

alter table "public"."events" alter column "price" set data type numeric;

alter table "public"."attendees" alter column "tournament_id" set data type bigint using "tournament_id"::bigint;

alter table "public"."bracket_phases" alter column "tournament_id" set data type bigint using "tournament_id"::bigint;

alter table "public"."contacts" alter column "id" drop default;

alter table "public"."contacts" alter column "id" add generated by default as identity;

alter table "public"."contacts" alter column "id" set data type bigint using "id"::bigint;

alter table "public"."discord_contact" alter column "contact_id" set data type bigint using "contact_id"::bigint;

alter table "public"."email_contacts" alter column "contact_id" set data type bigint using "contact_id"::bigint;

alter table "public"."entrants" alter column "tournament_id" set data type bigint using "tournament_id"::bigint;

alter table "public"."events" alter column "price" set data type money using "price"::money;

alter table "public"."events" alter column "tournament_id" set data type bigint using "tournament_id"::bigint;

alter table "public"."locations" alter column "id" drop default;

alter table "public"."locations" alter column "id" add generated by default as identity;

alter table "public"."locations" alter column "id" set data type bigint using "id"::bigint;

alter table "public"."match_slots" alter column "tournament_id" set data type bigint using "tournament_id"::bigint;

alter table "public"."matches" alter column "tournament_id" set data type bigint using "tournament_id"::bigint;

alter table "public"."offline_events" alter column "location_id" set data type bigint using "location_id"::bigint;

alter table "public"."offline_events" alter column "tournament_id" set data type bigint using "tournament_id"::bigint;

alter table "public"."offline_tournaments" alter column "location_id" set data type bigint using "location_id"::bigint;

alter table "public"."offline_tournaments" alter column "tournament_id" set data type bigint using "tournament_id"::bigint;

alter table "public"."online_events" alter column "tournament_id" set data type bigint using "tournament_id"::bigint;

alter table "public"."online_tournaments" alter column "tournament_id" set data type bigint using "tournament_id"::bigint;

alter table "public"."phase_groups" alter column "tournament_id" set data type bigint using "tournament_id"::bigint;

alter table "public"."seeds" alter column "tournament_id" set data type bigint using "tournament_id"::bigint;

alter table "public"."teams" alter column "tournament_id" set data type bigint using "tournament_id"::bigint;

alter table "public"."tournament_contacts" alter column "tournament_id" set data type bigint using "tournament_id"::bigint;

alter table "public"."tournaments" add column "home_page" text not null;

alter table "public"."waves" alter column "tournaments_id" set data type bigint using "tournaments_id"::bigint;

alter table "public"."email_contacts" alter column "email" set data type varchar(254) using "email"::varchar(254);

alter table "public"."users" alter column "email" set data type varchar(254) using "email"::varchar(254);

alter table "public"."discord_contact" alter column "invite_link" set data type varchar(8) using "invite_link"::varchar(8);

alter table "public"."attendees" drop constraint "attendees_users_fk_01";

alter table "public"."entrants" drop constraint "entrants_attendees_fk_01";

alter table "public"."seeds" drop constraint "seeds_entrants_fk_01";

alter table "public"."users" drop constraint "users_email_check";

alter table "public"."bracket_types" drop constraint "bracket_types_name_check";

alter table "public"."gaming_platforms" drop constraint "gaming_platforms_name_check";

alter table "public"."locations" drop constraint "locations_address_check";

alter table "public"."video_games" drop constraint "video_games_name_check";

alter table "public"."attendees" drop constraint "attendees_pk";

alter table "public"."entrants" drop constraint "entrants_pk";

alter table "public"."users" drop constraint "users_pk";

alter table "public"."attendees" drop column "user_email";

alter table "public"."attendees" add column "user_id" uuid not null;

alter table "public"."bracket_phases" alter column "bracket_type_name" set data type text using "bracket_type_name"::text;

alter table "public"."bracket_types" alter column "name" set data type text using "name"::text;

alter table "public"."entrants" drop column "user_email";

alter table "public"."entrants" add column "user_id" uuid not null;

alter table "public"."event_video_games" alter column "gaming_platform_name" set data type text using "gaming_platform_name"::text;

alter table "public"."event_video_games" alter column "video_game_name" set data type text using "video_game_name"::text;

alter table "public"."events" alter column "gaming_platform_name" set data type text using "gaming_platform_name"::text;

alter table "public"."events" alter column "video_game_name" set data type text using "video_game_name"::text;

alter table "public"."gaming_platforms" alter column "name" set data type text using "name"::text;

alter table "public"."locations" alter column "address" set data type text using "address"::text;

alter table "public"."seeds" drop column "entrant_user_email";

alter table "public"."seeds" add column "entrant_user_id" uuid;

alter table "public"."users" drop column "email";

alter table "public"."users" drop column "passhash";

alter table "public"."users" drop column "salt";

alter table "public"."users" add column "user_id" uuid not null;

alter table "public"."video_games" alter column "name" set data type text using "name"::text;

alter table "public"."attendees" add constraint "attendees_pk" PRIMARY KEY (tournament_id, user_id);

alter table "public"."entrants" add constraint "entrants_pk" PRIMARY KEY (tournament_id, event_name, user_id);

alter table "public"."users" add constraint "users_pk" PRIMARY KEY (user_id);

alter table "public"."attendees" add constraint "attendees_users_fk_01" FOREIGN KEY (user_id) REFERENCES public.users(user_id) NOT DEFERRABLE INITIALLY IMMEDIATE;

alter table "public"."attendees" validate constraint "attendees_users_fk_01";

alter table "public"."entrants" add constraint "entrants_attendees_fk_01" FOREIGN KEY (tournament_id, user_id) REFERENCES public.attendees(tournament_id, user_id) NOT DEFERRABLE INITIALLY IMMEDIATE;

alter table "public"."entrants" validate constraint "entrants_attendees_fk_01";

alter table "public"."seeds" add constraint "seeds_entrants_fk_01" FOREIGN KEY (tournament_id, event_name, entrant_user_id) REFERENCES public.entrants(tournament_id, event_name, user_id) NOT DEFERRABLE INITIALLY IMMEDIATE;

alter table "public"."seeds" validate constraint "seeds_entrants_fk_01";

alter table "public"."users" add constraint "public.users_auth.users_fk_01" FOREIGN KEY (user_id) REFERENCES auth.users(id) NOT DEFERRABLE INITIALLY IMMEDIATE;

alter table "public"."users" validate constraint "public.users_auth.users_fk_01";

alter table "public"."bracket_types" add constraint "bracket_types_name_check" CHECK ((length(name) >= 3)) NOT DEFERRABLE INITIALLY IMMEDIATE;

alter table "public"."bracket_types" validate constraint "bracket_types_name_check";

alter table "public"."gaming_platforms" add constraint "gaming_platforms_name_check" CHECK ((length(name) >= 3)) NOT DEFERRABLE INITIALLY IMMEDIATE;

alter table "public"."gaming_platforms" validate constraint "gaming_platforms_name_check";

alter table "public"."locations" add constraint "locations_address_check" CHECK ((length(address) >= 3)) NOT DEFERRABLE INITIALLY IMMEDIATE;

alter table "public"."locations" validate constraint "locations_address_check";

alter table "public"."video_games" add constraint "video_games_name_check" CHECK ((length(name) >= 3)) NOT DEFERRABLE INITIALLY IMMEDIATE;

alter table "public"."video_games" validate constraint "video_games_name_check";
