create sequence "public"."contacts_id_seq";

drop policy "Enable delete for authenticated users based on owner" on "public"."tournaments";

drop policy "Enable insert for authenticated users based on owner" on "public"."tournaments";

drop policy "Enable read access for all users" on "public"."tournaments";

drop policy "Enable update for authenticated users based on owner" on "public"."tournaments";

drop policy "user_delete" on "public"."users";

drop policy "user_insert" on "public"."users";

drop policy "user_select" on "public"."users";

drop policy "user_update" on "public"."users";

alter table "public"."events" drop constraint "events_name_min_len_check";

alter table "public"."events" drop constraint "events_start_end_time_check";

alter table "public"."gaming_platforms" drop constraint "gaming_platforms_name_min_len_check";

alter table "public"."locations" drop constraint "locations_address_min_len_check";

alter table "public"."locations" drop constraint "locations_uk_03";

alter table "public"."matches" drop constraint "matches_match_slots_fk_01";

alter table "public"."tournaments" drop constraint "tournaments_name_min_len_check";

alter table "public"."tournaments" drop constraint "tournaments_one_of_two_contacts_check";

alter table "public"."tournaments" drop constraint "tournaments_slug_min_len_check";

alter table "public"."tournaments" drop constraint "tournaments_start_end_time_check";

alter table "public"."tournaments" drop constraint "tournaments_users_fk_01";

alter table "public"."video_games" drop constraint "video_games_name_min_len_check";

alter table "public"."attendees" drop constraint "attendees_tournaments_fk_01";

alter table "public"."bracket_phases" drop constraint "bracket_phases_events_fk_01";

alter table "public"."entrants" drop constraint "entrants_attendees_fk_01";

alter table "public"."entrants" drop constraint "entrants_events_fk_01";

alter table "public"."entrants" drop constraint "entrants_teams_fk_01";

alter table "public"."events" drop constraint "events_tournaments_fk_01";

alter table "public"."locations" drop constraint "locations_uk_01";

alter table "public"."match_slots" drop constraint "match_slots_matches_fk_01";

alter table "public"."match_slots" drop constraint "match_slots_seeds_fk_01";

alter table "public"."matches" drop constraint "matches_phase_groups_fk_01";

alter table "public"."offline_events" drop constraint "offline_events_events_fk_01";

alter table "public"."offline_tournaments" drop constraint "offline_tournaments_tournaments_fk_01";

alter table "public"."phase_groups" drop constraint "phase_groups_bracket_phases_fk_01";

alter table "public"."phase_groups" drop constraint "phase_groups_waves_fk_01";

alter table "public"."seeds" drop constraint "seeds_entrants_fk_01";

alter table "public"."seeds" drop constraint "seeds_events_fk_01";

alter table "public"."seeds" drop constraint "seeds_teams_fk_01";

alter table "public"."teams" drop constraint "teams_events_fk_01";

alter table "public"."users" drop constraint "public.users_auth.users_fk_01";

alter table "public"."waves" drop constraint "waves_tournaments_fk_01";

drop function if exists "public"."insert_event"(tournament_id bigint, name character varying, start_time timestamp with time zone, end_time timestamp with time zone, price numeric, video_game text, platform text, teams_allowed boolean, is_online boolean, max_team_size integer, place_id text, address text, latitude double precision, longitude double precision);

drop function if exists "public"."insert_tournament"(t_name character varying, t_start_time timestamp with time zone, t_end_time timestamp with time zone, is_online boolean, t_email character varying, t_discord character varying, t_slug character varying, t_place_id text, t_address text, t_latitude double precision, t_longitude double precision);

drop function if exists "public"."insert_wave"(w_tournament_id bigint, w_identifier character varying);

drop function if exists "public"."update_tournament"(t_id bigint, t_name character varying, t_start_time timestamp with time zone, t_end_time timestamp with time zone, is_online boolean, t_email character varying, t_discord character varying, t_slug character varying, t_place_id text, t_address text, t_latitude double precision, t_longitude double precision);

drop function if exists "public"."update_wave"(w_tournament_id bigint, w_old_identifier character varying, w_new_identifier character varying);

alter table "public"."waves" drop constraint "waves_pk";

drop index if exists "public"."locations_uk_03";

drop index if exists "public"."locations_uk_01";

drop index if exists "public"."waves_pk";


  create table "public"."contacts" (
    "id" bigint generated by default as identity not null
      );


alter table "public"."contacts" enable row level security;


  create table "public"."discord_contact" (
    "contact_id" bigint not null,
    "invite_link" character varying(8) not null
      );


alter table "public"."discord_contact" enable row level security;


  create table "public"."email_contacts" (
    "contact_id" bigint not null,
    "email" character varying(254) not null
      );


alter table "public"."email_contacts" enable row level security;


  create table "public"."forum_posts" (
    "id" uuid not null default gen_random_uuid(),
    "thread_id" uuid not null,
    "author_id" uuid not null,
    "content" text not null default ''::text,
    "created_at" timestamp without time zone not null default now()
      );


alter table "public"."forum_posts" enable row level security;


  create table "public"."forum_thread" (
    "id" uuid not null default gen_random_uuid(),
    "author_id" uuid not null,
    "title" character varying not null,
    "content" text not null,
    "created_at" timestamp without time zone not null default now()
      );


alter table "public"."forum_thread" enable row level security;


  create table "public"."online_events" (
    "tournament_id" bigint not null,
    "event_name" character varying(80) not null
      );


alter table "public"."online_events" enable row level security;


  create table "public"."online_tournaments" (
    "tournament_id" bigint not null
      );


alter table "public"."online_tournaments" enable row level security;


  create table "public"."tournament_contacts" (
    "tournament_id" bigint not null,
    "contact_id" integer not null
      );


alter table "public"."tournament_contacts" enable row level security;

alter table "public"."events" add column "description" character varying(1024) not null;

alter table "public"."events" alter column "price" set data type money using "price"::money;

alter table "public"."locations" drop column "latitude";

alter table "public"."locations" drop column "longitude";

alter table "public"."locations" drop column "maps_place_id";

alter table "public"."locations" add column "coordinates" point not null;

alter table "public"."locations" add column "mapsplaceid" text not null;

alter table "public"."phase_groups" alter column "wave_identifier" set not null;

alter table "public"."tournaments" drop column "discord_invite";

alter table "public"."tournaments" drop column "email_contact";

alter table "public"."tournaments" drop column "owner";

alter table "public"."tournaments" alter column "home_page" drop default;

alter table "public"."tournaments" alter column "slug" set not null;

alter table "public"."waves" drop column "tournament_id";

alter table "public"."waves" add column "tournaments_id" bigint not null;

alter sequence "public"."contacts_id_seq" owned by "public"."contacts"."id";

CREATE UNIQUE INDEX contacts_pk ON public.contacts USING btree (id);

CREATE UNIQUE INDEX discord_contact_pk ON public.discord_contact USING btree (contact_id);

CREATE UNIQUE INDEX discord_contact_uk_01 ON public.discord_contact USING btree (invite_link);

CREATE UNIQUE INDEX email_contacts_pk ON public.email_contacts USING btree (contact_id);

CREATE UNIQUE INDEX email_contacts_uk_01 ON public.email_contacts USING btree (email);

CREATE UNIQUE INDEX forum_posts_pkey ON public.forum_posts USING btree (id);

CREATE UNIQUE INDEX forum_thread_pkey ON public.forum_thread USING btree (id);

CREATE UNIQUE INDEX online_events_pk ON public.online_events USING btree (tournament_id, event_name);

CREATE UNIQUE INDEX online_tournaments_pk ON public.online_tournaments USING btree (tournament_id);

CREATE UNIQUE INDEX tournament_contacts_pk ON public.tournament_contacts USING btree (tournament_id, contact_id);

CREATE UNIQUE INDEX locations_uk_01 ON public.locations USING btree (mapsplaceid);

CREATE UNIQUE INDEX waves_pk ON public.waves USING btree (identifier, tournaments_id);

alter table "public"."contacts" add constraint "contacts_pk" PRIMARY KEY using index "contacts_pk";

alter table "public"."discord_contact" add constraint "discord_contact_pk" PRIMARY KEY using index "discord_contact_pk";

alter table "public"."email_contacts" add constraint "email_contacts_pk" PRIMARY KEY using index "email_contacts_pk";

alter table "public"."forum_posts" add constraint "forum_posts_pkey" PRIMARY KEY using index "forum_posts_pkey";

alter table "public"."forum_thread" add constraint "forum_thread_pkey" PRIMARY KEY using index "forum_thread_pkey";

alter table "public"."online_events" add constraint "online_events_pk" PRIMARY KEY using index "online_events_pk";

alter table "public"."online_tournaments" add constraint "online_tournaments_pk" PRIMARY KEY using index "online_tournaments_pk";

alter table "public"."tournament_contacts" add constraint "tournament_contacts_pk" PRIMARY KEY using index "tournament_contacts_pk";

alter table "public"."waves" add constraint "waves_pk" PRIMARY KEY using index "waves_pk";

alter table "public"."discord_contact" add constraint "discord_contact_contacts_fk_01" FOREIGN KEY (contact_id) REFERENCES public.contacts(id) not valid;

alter table "public"."discord_contact" validate constraint "discord_contact_contacts_fk_01";

alter table "public"."discord_contact" add constraint "discord_contact_uk_01" UNIQUE using index "discord_contact_uk_01";

alter table "public"."email_contacts" add constraint "email_contacts_contacts_fk_01" FOREIGN KEY (contact_id) REFERENCES public.contacts(id) not valid;

alter table "public"."email_contacts" validate constraint "email_contacts_contacts_fk_01";

alter table "public"."email_contacts" add constraint "email_contacts_uk_01" UNIQUE using index "email_contacts_uk_01";

alter table "public"."events" add constraint "events_check" CHECK ((start_time < end_time)) not valid;

alter table "public"."events" validate constraint "events_check";

alter table "public"."events" add constraint "events_name_check" CHECK ((length((name)::text) >= 3)) not valid;

alter table "public"."events" validate constraint "events_name_check";

alter table "public"."forum_posts" add constraint "forum_posts_author_id_fkey" FOREIGN KEY (author_id) REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."forum_posts" validate constraint "forum_posts_author_id_fkey";

alter table "public"."forum_posts" add constraint "forum_posts_thread_id_fkey" FOREIGN KEY (thread_id) REFERENCES public.forum_thread(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."forum_posts" validate constraint "forum_posts_thread_id_fkey";

alter table "public"."forum_thread" add constraint "forum_thread_author_id_fkey" FOREIGN KEY (author_id) REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."forum_thread" validate constraint "forum_thread_author_id_fkey";

alter table "public"."gaming_platforms" add constraint "gaming_platforms_name_check" CHECK ((length(name) >= 3)) not valid;

alter table "public"."gaming_platforms" validate constraint "gaming_platforms_name_check";

alter table "public"."locations" add constraint "locations_address_check" CHECK ((length(address) >= 3)) not valid;

alter table "public"."locations" validate constraint "locations_address_check";

alter table "public"."matches" add constraint "matches_match_slots" FOREIGN KEY (advance_match_identifier, tournament_id, event_name, phase_group_identifier, advance_slot_num) REFERENCES public.match_slots(match_identifier, tournament_id, event_name, phase_group_identifier, slot_num) not valid;

alter table "public"."matches" validate constraint "matches_match_slots";

alter table "public"."online_events" add constraint "online_events_events_fk_01" FOREIGN KEY (tournament_id, event_name) REFERENCES public.events(tournament_id, name) not valid;

alter table "public"."online_events" validate constraint "online_events_events_fk_01";

alter table "public"."online_tournaments" add constraint "online_tournaments_tournaments_fk_01" FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id) not valid;

alter table "public"."online_tournaments" validate constraint "online_tournaments_tournaments_fk_01";

alter table "public"."tournament_contacts" add constraint "tournament_contacts_contacts_fk_01" FOREIGN KEY (contact_id) REFERENCES public.contacts(id) not valid;

alter table "public"."tournament_contacts" validate constraint "tournament_contacts_contacts_fk_01";

alter table "public"."tournament_contacts" add constraint "tournament_contacts_tournaments_fk_01" FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id) not valid;

alter table "public"."tournament_contacts" validate constraint "tournament_contacts_tournaments_fk_01";

alter table "public"."tournaments" add constraint "tournaments_check" CHECK ((start_time < end_time)) not valid;

alter table "public"."tournaments" validate constraint "tournaments_check";

alter table "public"."tournaments" add constraint "tournaments_name_check" CHECK ((length((name)::text) >= 3)) not valid;

alter table "public"."tournaments" validate constraint "tournaments_name_check";

alter table "public"."tournaments" add constraint "tournaments_slug_check" CHECK ((length((slug)::text) >= 3)) not valid;

alter table "public"."tournaments" validate constraint "tournaments_slug_check";

alter table "public"."video_games" add constraint "video_games_name_check" CHECK ((length(name) >= 3)) not valid;

alter table "public"."video_games" validate constraint "video_games_name_check";

alter table "public"."attendees" add constraint "attendees_tournaments_fk_01" FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id) not valid;

alter table "public"."attendees" validate constraint "attendees_tournaments_fk_01";

alter table "public"."bracket_phases" add constraint "bracket_phases_events_fk_01" FOREIGN KEY (tournament_id, event_name) REFERENCES public.events(tournament_id, name) not valid;

alter table "public"."bracket_phases" validate constraint "bracket_phases_events_fk_01";

alter table "public"."entrants" add constraint "entrants_attendees_fk_01" FOREIGN KEY (tournament_id, user_id) REFERENCES public.attendees(tournament_id, user_id) not valid;

alter table "public"."entrants" validate constraint "entrants_attendees_fk_01";

alter table "public"."entrants" add constraint "entrants_events_fk_01" FOREIGN KEY (tournament_id, event_name) REFERENCES public.events(tournament_id, name) not valid;

alter table "public"."entrants" validate constraint "entrants_events_fk_01";

alter table "public"."entrants" add constraint "entrants_teams_fk_01" FOREIGN KEY (team_name, tournament_id, event_name) REFERENCES public.teams(name, tournament_id, event_name) not valid;

alter table "public"."entrants" validate constraint "entrants_teams_fk_01";

alter table "public"."events" add constraint "events_tournaments_fk_01" FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id) not valid;

alter table "public"."events" validate constraint "events_tournaments_fk_01";

alter table "public"."locations" add constraint "locations_uk_01" UNIQUE using index "locations_uk_01";

alter table "public"."match_slots" add constraint "match_slots_matches_fk_01" FOREIGN KEY (match_identifier, tournament_id, event_name, phase_group_identifier) REFERENCES public.matches(identifier, tournament_id, event_name, phase_group_identifier) not valid;

alter table "public"."match_slots" validate constraint "match_slots_matches_fk_01";

alter table "public"."match_slots" add constraint "match_slots_seeds_fk_01" FOREIGN KEY (seed_num, tournament_id, event_name) REFERENCES public.seeds(seed_num, tournament_id, event_name) not valid;

alter table "public"."match_slots" validate constraint "match_slots_seeds_fk_01";

alter table "public"."matches" add constraint "matches_phase_groups_fk_01" FOREIGN KEY (phase_group_identifier, tournament_id, event_name) REFERENCES public.phase_groups(identifier, tournament_id, event_name) not valid;

alter table "public"."matches" validate constraint "matches_phase_groups_fk_01";

alter table "public"."offline_events" add constraint "offline_events_events_fk_01" FOREIGN KEY (tournament_id, event_name) REFERENCES public.events(tournament_id, name) not valid;

alter table "public"."offline_events" validate constraint "offline_events_events_fk_01";

alter table "public"."offline_tournaments" add constraint "offline_tournaments_tournaments_fk_01" FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id) not valid;

alter table "public"."offline_tournaments" validate constraint "offline_tournaments_tournaments_fk_01";

alter table "public"."phase_groups" add constraint "phase_groups_bracket_phases_fk_01" FOREIGN KEY (bracket_phase_name, tournament_id, event_name) REFERENCES public.bracket_phases(name, tournament_id, event_name) not valid;

alter table "public"."phase_groups" validate constraint "phase_groups_bracket_phases_fk_01";

alter table "public"."phase_groups" add constraint "phase_groups_waves_fk_01" FOREIGN KEY (wave_identifier, tournament_id) REFERENCES public.waves(identifier, tournaments_id) not valid;

alter table "public"."phase_groups" validate constraint "phase_groups_waves_fk_01";

alter table "public"."seeds" add constraint "seeds_entrants_fk_01" FOREIGN KEY (tournament_id, event_name, entrant_user_id) REFERENCES public.entrants(tournament_id, event_name, user_id) not valid;

alter table "public"."seeds" validate constraint "seeds_entrants_fk_01";

alter table "public"."seeds" add constraint "seeds_events_fk_01" FOREIGN KEY (tournament_id, event_name) REFERENCES public.events(tournament_id, name) not valid;

alter table "public"."seeds" validate constraint "seeds_events_fk_01";

alter table "public"."seeds" add constraint "seeds_teams_fk_01" FOREIGN KEY (team_name, tournament_id, event_name) REFERENCES public.teams(name, tournament_id, event_name) not valid;

alter table "public"."seeds" validate constraint "seeds_teams_fk_01";

alter table "public"."teams" add constraint "teams_events_fk_01" FOREIGN KEY (tournament_id, event_name) REFERENCES public.events(tournament_id, name) not valid;

alter table "public"."teams" validate constraint "teams_events_fk_01";

alter table "public"."users" add constraint "public.users_auth.users_fk_01" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."users" validate constraint "public.users_auth.users_fk_01";

alter table "public"."waves" add constraint "waves_tournaments_fk_01" FOREIGN KEY (tournaments_id) REFERENCES public.tournaments(id) not valid;

alter table "public"."waves" validate constraint "waves_tournaments_fk_01";

grant delete on table "public"."contacts" to "anon";

grant insert on table "public"."contacts" to "anon";

grant references on table "public"."contacts" to "anon";

grant select on table "public"."contacts" to "anon";

grant trigger on table "public"."contacts" to "anon";

grant truncate on table "public"."contacts" to "anon";

grant update on table "public"."contacts" to "anon";

grant delete on table "public"."contacts" to "authenticated";

grant insert on table "public"."contacts" to "authenticated";

grant references on table "public"."contacts" to "authenticated";

grant select on table "public"."contacts" to "authenticated";

grant trigger on table "public"."contacts" to "authenticated";

grant truncate on table "public"."contacts" to "authenticated";

grant update on table "public"."contacts" to "authenticated";

grant delete on table "public"."contacts" to "service_role";

grant insert on table "public"."contacts" to "service_role";

grant references on table "public"."contacts" to "service_role";

grant select on table "public"."contacts" to "service_role";

grant trigger on table "public"."contacts" to "service_role";

grant truncate on table "public"."contacts" to "service_role";

grant update on table "public"."contacts" to "service_role";

grant delete on table "public"."discord_contact" to "anon";

grant insert on table "public"."discord_contact" to "anon";

grant references on table "public"."discord_contact" to "anon";

grant select on table "public"."discord_contact" to "anon";

grant trigger on table "public"."discord_contact" to "anon";

grant truncate on table "public"."discord_contact" to "anon";

grant update on table "public"."discord_contact" to "anon";

grant delete on table "public"."discord_contact" to "authenticated";

grant insert on table "public"."discord_contact" to "authenticated";

grant references on table "public"."discord_contact" to "authenticated";

grant select on table "public"."discord_contact" to "authenticated";

grant trigger on table "public"."discord_contact" to "authenticated";

grant truncate on table "public"."discord_contact" to "authenticated";

grant update on table "public"."discord_contact" to "authenticated";

grant delete on table "public"."discord_contact" to "service_role";

grant insert on table "public"."discord_contact" to "service_role";

grant references on table "public"."discord_contact" to "service_role";

grant select on table "public"."discord_contact" to "service_role";

grant trigger on table "public"."discord_contact" to "service_role";

grant truncate on table "public"."discord_contact" to "service_role";

grant update on table "public"."discord_contact" to "service_role";

grant delete on table "public"."email_contacts" to "anon";

grant insert on table "public"."email_contacts" to "anon";

grant references on table "public"."email_contacts" to "anon";

grant select on table "public"."email_contacts" to "anon";

grant trigger on table "public"."email_contacts" to "anon";

grant truncate on table "public"."email_contacts" to "anon";

grant update on table "public"."email_contacts" to "anon";

grant delete on table "public"."email_contacts" to "authenticated";

grant insert on table "public"."email_contacts" to "authenticated";

grant references on table "public"."email_contacts" to "authenticated";

grant select on table "public"."email_contacts" to "authenticated";

grant trigger on table "public"."email_contacts" to "authenticated";

grant truncate on table "public"."email_contacts" to "authenticated";

grant update on table "public"."email_contacts" to "authenticated";

grant delete on table "public"."email_contacts" to "service_role";

grant insert on table "public"."email_contacts" to "service_role";

grant references on table "public"."email_contacts" to "service_role";

grant select on table "public"."email_contacts" to "service_role";

grant trigger on table "public"."email_contacts" to "service_role";

grant truncate on table "public"."email_contacts" to "service_role";

grant update on table "public"."email_contacts" to "service_role";

grant delete on table "public"."forum_posts" to "anon";

grant insert on table "public"."forum_posts" to "anon";

grant references on table "public"."forum_posts" to "anon";

grant select on table "public"."forum_posts" to "anon";

grant trigger on table "public"."forum_posts" to "anon";

grant truncate on table "public"."forum_posts" to "anon";

grant update on table "public"."forum_posts" to "anon";

grant delete on table "public"."forum_posts" to "authenticated";

grant insert on table "public"."forum_posts" to "authenticated";

grant references on table "public"."forum_posts" to "authenticated";

grant select on table "public"."forum_posts" to "authenticated";

grant trigger on table "public"."forum_posts" to "authenticated";

grant truncate on table "public"."forum_posts" to "authenticated";

grant update on table "public"."forum_posts" to "authenticated";

grant delete on table "public"."forum_posts" to "postgres";

grant insert on table "public"."forum_posts" to "postgres";

grant references on table "public"."forum_posts" to "postgres";

grant select on table "public"."forum_posts" to "postgres";

grant trigger on table "public"."forum_posts" to "postgres";

grant truncate on table "public"."forum_posts" to "postgres";

grant update on table "public"."forum_posts" to "postgres";

grant delete on table "public"."forum_posts" to "service_role";

grant insert on table "public"."forum_posts" to "service_role";

grant references on table "public"."forum_posts" to "service_role";

grant select on table "public"."forum_posts" to "service_role";

grant trigger on table "public"."forum_posts" to "service_role";

grant truncate on table "public"."forum_posts" to "service_role";

grant update on table "public"."forum_posts" to "service_role";

grant delete on table "public"."forum_thread" to "anon";

grant insert on table "public"."forum_thread" to "anon";

grant references on table "public"."forum_thread" to "anon";

grant select on table "public"."forum_thread" to "anon";

grant trigger on table "public"."forum_thread" to "anon";

grant truncate on table "public"."forum_thread" to "anon";

grant update on table "public"."forum_thread" to "anon";

grant delete on table "public"."forum_thread" to "authenticated";

grant insert on table "public"."forum_thread" to "authenticated";

grant references on table "public"."forum_thread" to "authenticated";

grant select on table "public"."forum_thread" to "authenticated";

grant trigger on table "public"."forum_thread" to "authenticated";

grant truncate on table "public"."forum_thread" to "authenticated";

grant update on table "public"."forum_thread" to "authenticated";

grant delete on table "public"."forum_thread" to "postgres";

grant insert on table "public"."forum_thread" to "postgres";

grant references on table "public"."forum_thread" to "postgres";

grant select on table "public"."forum_thread" to "postgres";

grant trigger on table "public"."forum_thread" to "postgres";

grant truncate on table "public"."forum_thread" to "postgres";

grant update on table "public"."forum_thread" to "postgres";

grant delete on table "public"."forum_thread" to "service_role";

grant insert on table "public"."forum_thread" to "service_role";

grant references on table "public"."forum_thread" to "service_role";

grant select on table "public"."forum_thread" to "service_role";

grant trigger on table "public"."forum_thread" to "service_role";

grant truncate on table "public"."forum_thread" to "service_role";

grant update on table "public"."forum_thread" to "service_role";

grant delete on table "public"."online_events" to "anon";

grant insert on table "public"."online_events" to "anon";

grant references on table "public"."online_events" to "anon";

grant select on table "public"."online_events" to "anon";

grant trigger on table "public"."online_events" to "anon";

grant truncate on table "public"."online_events" to "anon";

grant update on table "public"."online_events" to "anon";

grant delete on table "public"."online_events" to "authenticated";

grant insert on table "public"."online_events" to "authenticated";

grant references on table "public"."online_events" to "authenticated";

grant select on table "public"."online_events" to "authenticated";

grant trigger on table "public"."online_events" to "authenticated";

grant truncate on table "public"."online_events" to "authenticated";

grant update on table "public"."online_events" to "authenticated";

grant delete on table "public"."online_events" to "service_role";

grant insert on table "public"."online_events" to "service_role";

grant references on table "public"."online_events" to "service_role";

grant select on table "public"."online_events" to "service_role";

grant trigger on table "public"."online_events" to "service_role";

grant truncate on table "public"."online_events" to "service_role";

grant update on table "public"."online_events" to "service_role";

grant delete on table "public"."online_tournaments" to "anon";

grant insert on table "public"."online_tournaments" to "anon";

grant references on table "public"."online_tournaments" to "anon";

grant select on table "public"."online_tournaments" to "anon";

grant trigger on table "public"."online_tournaments" to "anon";

grant truncate on table "public"."online_tournaments" to "anon";

grant update on table "public"."online_tournaments" to "anon";

grant delete on table "public"."online_tournaments" to "authenticated";

grant insert on table "public"."online_tournaments" to "authenticated";

grant references on table "public"."online_tournaments" to "authenticated";

grant select on table "public"."online_tournaments" to "authenticated";

grant trigger on table "public"."online_tournaments" to "authenticated";

grant truncate on table "public"."online_tournaments" to "authenticated";

grant update on table "public"."online_tournaments" to "authenticated";

grant delete on table "public"."online_tournaments" to "service_role";

grant insert on table "public"."online_tournaments" to "service_role";

grant references on table "public"."online_tournaments" to "service_role";

grant select on table "public"."online_tournaments" to "service_role";

grant trigger on table "public"."online_tournaments" to "service_role";

grant truncate on table "public"."online_tournaments" to "service_role";

grant update on table "public"."online_tournaments" to "service_role";

grant delete on table "public"."tournament_contacts" to "anon";

grant insert on table "public"."tournament_contacts" to "anon";

grant references on table "public"."tournament_contacts" to "anon";

grant select on table "public"."tournament_contacts" to "anon";

grant trigger on table "public"."tournament_contacts" to "anon";

grant truncate on table "public"."tournament_contacts" to "anon";

grant update on table "public"."tournament_contacts" to "anon";

grant delete on table "public"."tournament_contacts" to "authenticated";

grant insert on table "public"."tournament_contacts" to "authenticated";

grant references on table "public"."tournament_contacts" to "authenticated";

grant select on table "public"."tournament_contacts" to "authenticated";

grant trigger on table "public"."tournament_contacts" to "authenticated";

grant truncate on table "public"."tournament_contacts" to "authenticated";

grant update on table "public"."tournament_contacts" to "authenticated";

grant delete on table "public"."tournament_contacts" to "service_role";

grant insert on table "public"."tournament_contacts" to "service_role";

grant references on table "public"."tournament_contacts" to "service_role";

grant select on table "public"."tournament_contacts" to "service_role";

grant trigger on table "public"."tournament_contacts" to "service_role";

grant truncate on table "public"."tournament_contacts" to "service_role";

grant update on table "public"."tournament_contacts" to "service_role";

drop trigger if exists "on_auth_user_created" on "auth"."users";

drop trigger if exists "protect_buckets_delete" on "storage"."buckets";

drop trigger if exists "protect_objects_delete" on "storage"."objects";

CREATE TRIGGER objects_delete_delete_prefix AFTER DELETE ON storage.objects FOR EACH ROW EXECUTE FUNCTION storage.delete_prefix_hierarchy_trigger();

CREATE TRIGGER objects_insert_create_prefix BEFORE INSERT ON storage.objects FOR EACH ROW EXECUTE FUNCTION storage.objects_insert_prefix_trigger();

CREATE TRIGGER objects_update_create_prefix BEFORE UPDATE ON storage.objects FOR EACH ROW WHEN (((new.name <> old.name) OR (new.bucket_id <> old.bucket_id))) EXECUTE FUNCTION storage.objects_update_prefix_trigger();

CREATE TRIGGER prefixes_create_hierarchy BEFORE INSERT ON storage.prefixes FOR EACH ROW WHEN ((pg_trigger_depth() < 1)) EXECUTE FUNCTION storage.prefixes_insert_trigger();

CREATE TRIGGER prefixes_delete_hierarchy AFTER DELETE ON storage.prefixes FOR EACH ROW EXECUTE FUNCTION storage.delete_prefix_hierarchy_trigger();


