alter table "public"."events" drop constraint "events_check";

alter table "public"."events" drop constraint "events_name_check";

alter table "public"."video_games" drop constraint "video_games_name_check";


  create table "public"."match_setups" (
    "identifier" character varying not null,
    "tournament_id" bigint not null,
    "event_id" smallint not null,
    "match_identifier" character varying,
    "phase_group_identifier" character varying
      );


alter table "public"."match_setups" enable row level security;


  create table "public"."schedule_conflicts" (
    "id" bigint generated by default as identity not null,
    "tournament_id" bigint not null,
    "user_id" uuid not null,
    "start_time" timestamp with time zone not null,
    "end_time" timestamp with time zone not null
      );


alter table "public"."schedule_conflicts" enable row level security;

alter table "public"."admins" add column "email" text not null default ''::text;

alter table "public"."forum_posts" disable row level security;

alter table "public"."forum_thread" disable row level security;

alter table "public"."tournaments" alter column "is_online" drop default;

alter table "public"."users" alter column "time_joined" drop default;

CREATE UNIQUE INDEX match_setups_pkey ON public.match_setups USING btree (identifier);

CREATE UNIQUE INDEX schedule_conflicts_pkey ON public.schedule_conflicts USING btree (id);

alter table "public"."match_setups" add constraint "match_setups_pkey" PRIMARY KEY using index "match_setups_pkey";

alter table "public"."schedule_conflicts" add constraint "schedule_conflicts_pkey" PRIMARY KEY using index "schedule_conflicts_pkey";

alter table "public"."entrants" add constraint "entrants_tournament_id_fkey" FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."entrants" validate constraint "entrants_tournament_id_fkey";

alter table "public"."events" add constraint "events_name_min_len_check" CHECK ((length((name)::text) >= 3)) not valid;

alter table "public"."events" validate constraint "events_name_min_len_check";

alter table "public"."events" add constraint "events_start_end_time_check" CHECK ((start_time < end_time)) not valid;

alter table "public"."events" validate constraint "events_start_end_time_check";

alter table "public"."match_setups" add constraint "match_setups_matches_fk" FOREIGN KEY (match_identifier, tournament_id, event_id, phase_group_identifier) REFERENCES public.matches(identifier, tournament_id, event_id, phase_group_identifier) not valid;

alter table "public"."match_setups" validate constraint "match_setups_matches_fk";

alter table "public"."match_setups" add constraint "match_setups_tournament_id_fkey" FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."match_setups" validate constraint "match_setups_tournament_id_fkey";

alter table "public"."schedule_conflicts" add constraint "schedule_conflicts_tournament_id_fkey" FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."schedule_conflicts" validate constraint "schedule_conflicts_tournament_id_fkey";

alter table "public"."schedule_conflicts" add constraint "schedule_conflicts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."schedule_conflicts" validate constraint "schedule_conflicts_user_id_fkey";

alter table "public"."video_games" add constraint "video_games_name_min_len_check" CHECK ((length(name) >= 3)) not valid;

alter table "public"."video_games" validate constraint "video_games_name_min_len_check";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_email_from_user_id(uid uuid)
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  RETURN (SELECT email FROM auth.users WHERE id = uid);
END;
$function$
;

CREATE OR REPLACE FUNCTION public.getuserfromemail(user_email text)
 RETURNS uuid
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
  SELECT id FROM auth.users WHERE email = user_email LIMIT 1;
$function$
;

CREATE OR REPLACE FUNCTION public.insert_admin(a_tournament_id bigint, a_user_id uuid, a_permission_level smallint)
 RETURNS void
 LANGUAGE plpgsql
AS $function$BEGIN
    INSERT INTO public.admins (tournament_id, user_id, permission_level)
    VALUES (a_tournament_id, a_user_id, a_permission_level);
END;$function$
;

CREATE OR REPLACE FUNCTION public.insert_schedule_conflict(s_tournament_id bigint, s_user_id uuid, s_start_time timestamp with time zone, s_end_time timestamp with time zone)
 RETURNS void
 LANGUAGE plpgsql
AS $function$BEGIN
    INSERT INTO public.schedule_conflicts (tournament_id, user_id, start_time, end_time)
    VALUES (s_tournament_id, s_user_id, s_start_time, s_end_time);
END;$function$
;

CREATE OR REPLACE FUNCTION public.insert_setups(s_identifier character varying, s_tournament_id bigint, s_event_id smallint, s_match_identifier character varying DEFAULT NULL::character varying, s_phase_group_identifier character varying DEFAULT NULL::character varying)
 RETURNS void
 LANGUAGE plpgsql
AS $function$BEGIN
    INSERT INTO public.match_setups (
        identifier, tournament_id, event_id, match_identifier, phase_group_identifier
    )
    VALUES (s_identifier, s_tournament_id, s_event_id, s_match_identifier, s_phase_group_identifier);
END;$function$
;

CREATE OR REPLACE FUNCTION public.update_admins(a_tournament_id bigint, a_user_id uuid, a_permission_level smallint)
 RETURNS void
 LANGUAGE plpgsql
AS $function$BEGIN
    UPDATE public.admins
    SET permission_level = a_permission_level
    WHERE tournament_id = a_tournament_id
    AND user_id = a_user_id;
END;$function$
;

CREATE OR REPLACE FUNCTION public.update_schedule_conflict(s_tournament_id bigint, s_user_id uuid, s_start_time timestamp with time zone, s_end_time timestamp with time zone, s_id bigint)
 RETURNS void
 LANGUAGE plpgsql
AS $function$BEGIN
  UPDATE public.schedule_conflicts
  SET
    tournament_id = s_tournament_id,
    user_id = s_user_id,
    start_time = s_start_time,
    end_time = s_end_time
  WHERE id = s_id;
END;$function$
;

CREATE OR REPLACE FUNCTION public.update_setup(s_identifier character varying, s_tournament_id bigint, s_event_id smallint, s_match_identifier character varying DEFAULT NULL::character varying, s_phase_group_identifier character varying DEFAULT NULL::character varying)
 RETURNS void
 LANGUAGE plpgsql
AS $function$BEGIN
    UPDATE public.match_setups
    SET 
        match_identifier = s_match_identifier,
        phase_group_identifier = s_phase_group_identifier
    WHERE 
        identifier = s_identifier
        AND tournament_id = s_tournament_id
        AND event_id = s_event_id;
END;$function$
;

CREATE OR REPLACE FUNCTION public.update_user(u_prefix character varying, u_display_name character varying, u_first_name character varying, u_last_name character varying, u_state character varying, u_country character varying, u_show_results boolean)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
    UPDATE public.users
    SET
        prefix = u_prefix,
        display_name = u_display_name,
        first_name = u_first_name,
        last_name = u_last_name,
        state = u_state,
        country = u_country,
        show_results = u_show_results
    WHERE user_id = auth.uid();
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  INSERT INTO public.users (user_id, first_name, last_name, display_name, prefix, time_joined)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'first_name', 'Unknown'),
    COALESCE(NEW.raw_user_meta_data->>'last_name', 'Unknown'),
    COALESCE(NEW.raw_user_meta_data->>'display_name', split_part(NEW.email, '@', 1)),
    NEW.raw_user_meta_data->>'prefix',
    NOW()
  );
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.has_permission_level(tid bigint, uid uuid, plevel integer)
 RETURNS boolean
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
DECLARE
  level integer;
BEGIN
SELECT permission_level
FROM public.admins
WHERE (tournament_id = tid AND user_id = uid)
    INTO level;

IF level IS NULL THEN
    RETURN false;
END IF;

  IF level <= plevel THEN
    RETURN true;
END IF;

RETURN false;
END;$function$
;

CREATE OR REPLACE FUNCTION public.insert_event(e_tournament_id bigint, e_name character varying, e_start_time timestamp with time zone, e_end_time timestamp with time zone, e_price numeric, e_video_game_name text, e_gaming_platform_name text, e_teams_allowed boolean, e_max_team_size smallint DEFAULT NULL::smallint)
 RETURNS smallint
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
DECLARE
    e_id smallint;
    bp_id smallint;
BEGIN
    INSERT INTO public.events (tournament_id, name, start_time, end_time, price, video_game_name, gaming_platform_name, teams_allowed, max_team_size)
    VALUES (e_tournament_id, e_name, e_start_time, e_end_time, e_price, e_video_game_name, e_gaming_platform_name, e_teams_allowed, e_max_team_size)
        RETURNING id
    INTO e_id;

    INSERT INTO public.bracket_phases (tournament_id, event_id, name, num_progressing_per_group, bracket_type_name, next_phase_id)
    VALUES (e_tournament_id, e_id, 'Bracket', 1, 'Single Elimination', NULL)
        RETURNING id
    INTO bp_id;

    INSERT INTO public.phase_groups (identifier, tournament_id, event_id, bracket_phase_id, wave_identifier)
    VALUES ('Bracket', e_tournament_id, e_id, bp_id, NULL);

    RETURN e_id;
END;$function$
;

CREATE OR REPLACE FUNCTION public.insert_post(p_thread_id uuid, p_content text)
 RETURNS void
 LANGUAGE plpgsql
AS $function$BEGIN
    INSERT INTO public.forum_posts(thread_id, author_id, content)
    VALUES (p_thread_id, auth.uid(), p_content);
END;$function$
;

CREATE OR REPLACE FUNCTION public.insert_thread(t_title character varying, t_content text)
 RETURNS void
 LANGUAGE plpgsql
AS $function$DECLARE 
    gen_thread_id uuid;
BEGIN
    INSERT INTO public.forum_thread(author_id, title, content)
    VALUES (auth.uid(), t_title, t_content)
    RETURNING id into gen_thread_id;

    INSERT INTO public.forum_posts(thread_id, author_id, content)
    VALUES (gen_thread_id, auth.uid(), t_content);
END;$function$
;

CREATE OR REPLACE FUNCTION public.insert_tournament(t_name character varying, t_start_time timestamp with time zone, t_end_time timestamp with time zone, t_is_online boolean, t_is_public boolean, t_email character varying DEFAULT NULL::character varying, t_discord character varying DEFAULT NULL::character varying, t_slug character varying DEFAULT NULL::character varying, t_place_id text DEFAULT NULL::text, t_address text DEFAULT NULL::text, t_latitude double precision DEFAULT NULL::double precision, t_longitude double precision DEFAULT NULL::double precision)
 RETURNS bigint
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$DECLARE
    t_id bigint;
    loc_id bigint;
BEGIN

IF t_is_online = false THEN
SELECT id
INTO loc_id
FROM public.locations
WHERE maps_place_id = t_place_id;

IF loc_id IS NULL THEN
            INSERT INTO public.locations (maps_place_id, address, latitude, longitude)
            VALUES (t_place_id, t_address, t_latitude, t_longitude)
            RETURNING id
            INTO loc_id;
END IF;
END IF;

INSERT INTO public.tournaments (name, start_time, end_time, slug, email_contact, discord_invite, owner, is_public, is_online, location_id)
VALUES (t_name, t_start_time, t_end_time, t_slug, t_email, t_discord, auth.uid(), t_is_public, t_is_online, loc_id)
    RETURNING id
INTO t_id;

INSERT INTO public.admins (tournament_id, user_id, permission_level)
VALUES (t_id, auth.uid(), 0);

RETURN t_id;
END;$function$
;

CREATE OR REPLACE FUNCTION public.insert_wave(w_tournament_id bigint, w_identifier character varying)
 RETURNS void
 LANGUAGE plpgsql
AS $function$BEGIN
    INSERT INTO public.waves (tournament_id, identifier)
    VALUES (w_tournament_id, w_identifier);
END;$function$
;

CREATE OR REPLACE FUNCTION public.update_event(e_tournament_id bigint, e_id smallint, e_name character varying, e_start_time timestamp with time zone, e_end_time timestamp with time zone, e_price numeric, e_video_game_name text, e_gaming_platform_name text, e_teams_allowed boolean, e_max_team_size smallint DEFAULT NULL::smallint)
 RETURNS smallint
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
BEGIN

UPDATE public.events
SET name = e_name, start_time = e_start_time, end_time = e_end_time, price = e_price, video_game_name = e_video_game_name,
    gaming_platform_name = e_gaming_platform_name, teams_allowed = e_teams_allowed, max_team_size = e_max_team_size
WHERE tournament_id = e_tournament_id AND id = e_id;

RETURN e_id;
END;$function$
;

CREATE OR REPLACE FUNCTION public.update_post(p_post_id uuid, p_new_content text)
 RETURNS void
 LANGUAGE plpgsql
AS $function$BEGIN
    UPDATE public.forum_posts
    SET content = p_new_content
    WHERE id = p_post_id AND author_id = auth.uid();
END;$function$
;

CREATE OR REPLACE FUNCTION public.update_tournament(t_id bigint, t_name character varying, t_start_time timestamp with time zone, t_end_time timestamp with time zone, t_is_online boolean, t_is_public boolean, t_email character varying DEFAULT NULL::character varying, t_discord character varying DEFAULT NULL::character varying, t_slug character varying DEFAULT NULL::character varying, t_place_id text DEFAULT NULL::text, t_address text DEFAULT NULL::text, t_latitude double precision DEFAULT NULL::double precision, t_longitude double precision DEFAULT NULL::double precision)
 RETURNS bigint
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$DECLARE
    loc_id bigint;
BEGIN

IF t_is_online = false THEN
SELECT id
INTO loc_id
FROM public.locations
WHERE maps_place_id = t_place_id;

IF loc_id IS NULL THEN
                INSERT INTO public.locations (maps_place_id, address, latitude, longitude)
                VALUES (t_place_id, t_address, t_latitude, t_longitude)
                RETURNING id
                INTO loc_id;
END IF;
END IF;

UPDATE public.tournaments
SET name = t_name, start_time = t_start_time, end_time = t_end_time, slug = t_slug, email_contact = t_email, discord_invite = t_discord, is_public = t_is_public, is_online = t_is_online, location_id = loc_id
WHERE id = t_id;

RETURN t_id;
END;$function$
;

CREATE OR REPLACE FUNCTION public.update_wave(w_tournament_id bigint, w_old_identifier character varying, w_new_identifier character varying)
 RETURNS void
 LANGUAGE plpgsql
AS $function$BEGIN
    UPDATE public.waves
    SET identifier = w_new_identifier
    WHERE tournament_id = w_tournament_id AND identifier = w_old_identifier;
END;$function$
;

grant delete on table "public"."match_setups" to "anon";

grant insert on table "public"."match_setups" to "anon";

grant references on table "public"."match_setups" to "anon";

grant select on table "public"."match_setups" to "anon";

grant trigger on table "public"."match_setups" to "anon";

grant truncate on table "public"."match_setups" to "anon";

grant update on table "public"."match_setups" to "anon";

grant delete on table "public"."match_setups" to "authenticated";

grant insert on table "public"."match_setups" to "authenticated";

grant references on table "public"."match_setups" to "authenticated";

grant select on table "public"."match_setups" to "authenticated";

grant trigger on table "public"."match_setups" to "authenticated";

grant truncate on table "public"."match_setups" to "authenticated";

grant update on table "public"."match_setups" to "authenticated";

grant delete on table "public"."match_setups" to "service_role";

grant insert on table "public"."match_setups" to "service_role";

grant references on table "public"."match_setups" to "service_role";

grant select on table "public"."match_setups" to "service_role";

grant trigger on table "public"."match_setups" to "service_role";

grant truncate on table "public"."match_setups" to "service_role";

grant update on table "public"."match_setups" to "service_role";

grant delete on table "public"."schedule_conflicts" to "anon";

grant insert on table "public"."schedule_conflicts" to "anon";

grant references on table "public"."schedule_conflicts" to "anon";

grant select on table "public"."schedule_conflicts" to "anon";

grant trigger on table "public"."schedule_conflicts" to "anon";

grant truncate on table "public"."schedule_conflicts" to "anon";

grant update on table "public"."schedule_conflicts" to "anon";

grant delete on table "public"."schedule_conflicts" to "authenticated";

grant insert on table "public"."schedule_conflicts" to "authenticated";

grant references on table "public"."schedule_conflicts" to "authenticated";

grant select on table "public"."schedule_conflicts" to "authenticated";

grant trigger on table "public"."schedule_conflicts" to "authenticated";

grant truncate on table "public"."schedule_conflicts" to "authenticated";

grant update on table "public"."schedule_conflicts" to "authenticated";

grant delete on table "public"."schedule_conflicts" to "service_role";

grant insert on table "public"."schedule_conflicts" to "service_role";

grant references on table "public"."schedule_conflicts" to "service_role";

grant select on table "public"."schedule_conflicts" to "service_role";

grant trigger on table "public"."schedule_conflicts" to "service_role";

grant truncate on table "public"."schedule_conflicts" to "service_role";

grant update on table "public"."schedule_conflicts" to "service_role";


