alter table "public"."match_slots" drop constraint "match_slots_matches_fk_01";

alter table "public"."match_slots" drop constraint "match_slots_seeds_fk_01";

alter table "public"."matches" drop constraint "matches_match_slots_fk_01";

alter table "public"."matches" drop constraint "matches_phase_groups_fk_01";

alter table "public"."seeds" drop constraint "seeds_events_fk_01";

alter table "public"."match_slots" drop constraint "match_slots_pk";

alter table "public"."matches" drop constraint "matches_pk";

alter table "public"."seeds" drop constraint "seeds_pk";

drop index if exists "public"."match_slots_pk";

drop index if exists "public"."matches_pk";

drop index if exists "public"."seeds_pk";


create table "public"."rounds" (
                                   "tournament_id" bigint not null,
                                   "event_id" smallint not null,
                                   "phase_group_identifier" character varying not null,
                                   "round_num" integer not null
);


alter table "public"."rounds" enable row level security;

alter table "public"."matches" add column "round_num" integer not null;

alter table "public"."seeds" add column "phase_group_identifier" character varying not null;

alter table "public"."matches" drop column "identifier";

alter table "public"."matches" add column "code" varchar(8) not null;

alter table "public"."matches" add column "id" int generated by default as identity not null;

alter table "public"."match_slots" drop column "match_identifier";

alter table "public"."match_slots" add column "match_id" int not null;

alter table "public"."matches" drop column "advance_match_identifier";

alter table "public"."matches" add column "advance_match_id" int;

CREATE UNIQUE INDEX match_slots_pk ON public.match_slots USING btree (match_id, tournament_id, phase_group_identifier, slot_num, event_id);

CREATE UNIQUE INDEX matches_pk ON public.matches USING btree (id, tournament_id, phase_group_identifier, event_id);

CREATE UNIQUE INDEX rounds_pk ON public.rounds USING btree (tournament_id, event_id, phase_group_identifier, round_num);

CREATE UNIQUE INDEX seeds_pk ON public.seeds USING btree (seed_num, tournament_id, event_id, phase_group_identifier);

alter table "public"."match_slots" add constraint "match_slots_pk" PRIMARY KEY using index "match_slots_pk";

alter table "public"."matches" add constraint "matches_pk" PRIMARY KEY using index "matches_pk";

alter table "public"."rounds" add constraint "rounds_pk" PRIMARY KEY using index "rounds_pk";

alter table "public"."seeds" add constraint "seeds_pk" PRIMARY KEY using index "seeds_pk";

alter table "public"."match_slots" add constraint "match_slots_seeds_fk_01" FOREIGN KEY (tournament_id, event_id, phase_group_identifier, seed_num) REFERENCES public.seeds(tournament_id, event_id, phase_group_identifier, seed_num) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE;

alter table "public"."match_slots" add constraint "match_slots_phase_groups_fk_01" FOREIGN KEY (tournament_id, event_id, phase_group_identifier) REFERENCES public.phase_groups(tournament_id, event_id, identifier) NOT DEFERRABLE INITIALLY IMMEDIATE;

alter table "public"."matches" add constraint "matches_match_slots_fk_01" FOREIGN KEY (tournament_id, event_id, phase_group_identifier, advance_match_id, advance_slot_num) REFERENCES public.match_slots(tournament_id, event_id, phase_group_identifier, match_id, slot_num) ON UPDATE CASCADE ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE;

alter table "public"."matches" add constraint "matches_rounds_fk_01" FOREIGN KEY (tournament_id, event_id, phase_group_identifier, round_num) REFERENCES public.rounds(tournament_id, event_id, phase_group_identifier, round_num) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;

alter table "public"."rounds" add constraint "rounds_phase_groups_fk_01" FOREIGN KEY (tournament_id, event_id, phase_group_identifier) REFERENCES public.phase_groups(tournament_id, event_id, identifier) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;

alter table "public"."seeds" add constraint "seeds_phase_groups_fk_01" FOREIGN KEY (tournament_id, event_id, phase_group_identifier) REFERENCES public.phase_groups(tournament_id, event_id, identifier) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;

alter table "public"."match_slots" add constraint "match_slots_matches_fk_01" FOREIGN KEY (match_id, tournament_id, event_id, phase_group_identifier) REFERENCES public.matches(id, tournament_id, event_id, phase_group_identifier) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;

CREATE OR REPLACE FUNCTION public.register_user_for_tournament(tid bigint, eids smallint[], uid uuid)
    RETURNS void
    LANGUAGE plpgsql
    SET search_path to ''
AS $$
DECLARE
e smallint;
    snum int;
    bphaseid smallint;
    pgroupid varchar(8);
    matchid varchar(8);
BEGIN
INSERT INTO public.attendees (tournament_id, user_id)
VALUES (tid, uid);

FOREACH e IN ARRAY eids
    LOOP
        INSERT INTO public.entrants (tournament_id, event_id, user_id)
        VALUES (tid, e, uid);

SELECT id
INTO bphaseid
FROM public.bracket_phases
WHERE tournament_id = tid AND event_id = e AND
    id NOT IN (
        SELECT COALESCE(next_phase_id, -1)
        FROM public.bracket_phases
        WHERE tournament_id = tid AND event_id = e
    );

SELECT m.identifier
INTO pgroupid
FROM (
         SELECT c.identifier as identifier, MIN(c.num_matches)
         FROM (
                  SELECT phase_groups.identifier AS identifier, COUNT(matches.id) as num_matches
                  FROM public.phase_groups LEFT OUTER JOIN public.matches
                                                           ON (phase_groups.identifier = matches.phase_group_identifier AND phase_groups.tournament_id = matches.tournament_id AND phase_groups.event_id = matches.event_id)
                  WHERE phase_groups.tournament_id = tid AND phase_groups.event_id = e AND bracket_phase_id = bphaseid
                  GROUP BY phase_groups.identifier
              ) AS c
         GROUP BY c.identifier
     ) as m;

SELECT MIN(seed_num)
INTO snum
FROM public.seeds
WHERE tournament_id = tid and event_id = e and team_name is null and entrant_user_id is null;

IF snum IS NOT NULL THEN
UPDATE public.seeds
SET entrant_user_id = uid
WHERE tournament_id = tid AND event_id = e AND phase_group_identifier = pgroupid AND seed_num = snum;
ELSE
SELECT MAX(seed_num) + 1
INTO snum
FROM public.seeds
WHERE tournament_id = tid and event_id = e;

INSERT INTO public.seeds (seed_num, tournament_id, event_id, phase_group_identifier, entrant_user_id)
VALUES (snum, tid, e, pgroupid, uid);
END IF;

        PERFORM public.recreate_bracket(tid, e, pgroupid);
END LOOP;

    RETURN;
END;
$$;

CREATE OR REPLACE FUNCTION public.insert_event(e_tournament_id bigint, e_name character varying, e_start_time timestamp with time zone, e_end_time timestamp with time zone, e_price numeric, e_video_game_name text, e_gaming_platform_name text, e_teams_allowed boolean, e_max_team_size smallint DEFAULT NULL::smallint)
 RETURNS smallint
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
DECLARE
e_id smallint;
    bp_id smallint;
    pg_id varchar;
    m_id int;
BEGIN
-- Creates new event
INSERT INTO public.events (tournament_id, name, start_time, end_time, price, video_game_name, gaming_platform_name, teams_allowed, max_team_size)
VALUES (e_tournament_id, e_name, e_start_time, e_end_time, e_price, e_video_game_name, e_gaming_platform_name, e_teams_allowed, e_max_team_size)
    RETURNING id
INTO e_id;

-- Creates first bracket phase for said event
INSERT INTO public.bracket_phases (id, tournament_id, event_id, name, num_progressing_per_group, bracket_type_name, next_phase_id)
VALUES (1, e_tournament_id, e_id, 'Bracket', 1, 'Single Elimination', NULL)
    RETURNING id
INTO bp_id;

-- Creates first phase group for said bracket phase
INSERT INTO public.phase_groups (identifier, tournament_id, event_id, bracket_phase_id, wave_identifier)
VALUES ('1', e_tournament_id, e_id, bp_id, NULL)
    RETURNING identifier
INTO pg_id;

-- Creates first round and finals match for said phase group
INSERT INTO public.rounds (tournament_id, event_id, phase_group_identifier, round_num)
VALUES (e_tournament_id, e_id, pg_id, 1);

INSERT INTO public.matches (tournament_id, event_id, phase_group_identifier, code, round_num)
VALUES (e_tournament_id, e_id, pg_id, 'A', 1)
    RETURNING id
INTO m_id;

-- Creates seeds and match slots for said finals match
INSERT INTO public.seeds (tournament_id, event_id, phase_group_identifier, seed_num)
VALUES (e_tournament_id, e_id, pg_id, 1),
       (e_tournament_id, e_id, pg_id, 2);

INSERT INTO public.match_slots (tournament_id, event_id, phase_group_identifier, seed_num, match_id, slot_num)
VALUES (e_tournament_id, e_id, pg_id, 1, m_id, '1'),
       (e_tournament_id, e_id, pg_id, 2, m_id, '2');

RETURN e_id;
END;$function$
;


CREATE OR REPLACE FUNCTION public.recreate_bracket(tid bigint, eid smallint, pgid varchar(8))
       RETURNS void
       LANGUAGE plpgsql
       SET search_path TO ''
AS $function$
DECLARE
bpid smallint;
    btype text;
    rnum int;
    mcount int;
    mid int;
    curr_slot public.match_slots%ROWTYPE;
    snum int;
BEGIN
-- Find bracket type, which changes how to recreate the bracket
SELECT bracket_phase_id
INTO bpid
FROM public.phase_groups
WHERE tournament_id = tid AND event_id = eid AND identifier = pgid;

SELECT bracket_type_name
INTO btype
FROM public.bracket_phases
WHERE tournament_id = tid AND event_id = eid AND id = bpid;

IF btype = 'Single Elimination' THEN
   -- Repeat loop for every seed that has not been assigned a match slot
        FOR snum IN
            SELECT seeds.seed_num
            FROM public.seeds
            WHERE tournament_id = tid AND event_id = eid AND phase_group_identifier = pgid
              AND seeds.seed_num NOT IN (
                SELECT COALESCE(match_slots.seed_num, 0)
                FROM public.match_slots
                WHERE tournament_id = tid AND event_id = eid AND phase_group_identifier = pgid
            )
            ORDER BY seeds.seed_num
        LOOP
            -- Finds the earliest existing round number
            SELECT MAX(round_num)
            INTO rnum
            FROM public.rounds
            WHERE tournament_id = tid AND event_id = eid AND phase_group_identifier = pgid;

            -- Check if earliest round is filled up (equal to a power of 2). If so, add a new round
            SELECT COUNT(*)
            INTO mcount
            FROM public.matches
            WHERE tournament_id = tid AND event_id = eid AND phase_group_identifier = pgid AND round_num = rnum;

            IF mcount = 2^(rnum - 1) THEN
                            rnum := rnum + 1;
            INSERT INTO public.rounds (tournament_id, event_id, phase_group_identifier, round_num)
            VALUES (tid, eid, pgid, rnum);
            END IF;

            -- Increments the match code of every match
            UPDATE public.matches
            SET code = public.inc_code(code)
            WHERE tournament_id = tid AND event_id = eid AND phase_group_identifier = pgid;

            -- Find the lowest seed in the 2nd earliest round to move back a round
            SELECT *
            INTO curr_slot
            FROM public.match_slots
            WHERE tournament_id = tid AND event_id = eid AND phase_group_identifier = pgid
              AND seed_num = (
                SELECT MAX(seed_num)
                FROM public.match_slots INNER JOIN public.matches
                                                   ON (match_slots.tournament_id = matches.tournament_id AND match_slots.event_id = matches.event_id AND
                                                       match_slots.phase_group_identifier = matches.phase_group_identifier AND match_slots.match_id = matches.id)
                WHERE match_slots.tournament_id = tid AND match_slots.event_id = eid AND match_slots.phase_group_identifier = pgid AND matches.round_num = rnum - 1
            );

            -- Moves seed found in the last query and the new unadded seed into a new match
            UPDATE public.match_slots
            SET seed_num = NULL
            WHERE tournament_id = curr_slot.tournament_id AND event_id = curr_slot.event_id AND phase_group_identifier = curr_slot.phase_group_identifier
              AND match_id = curr_slot.match_id AND slot_num = curr_slot.slot_num;

            INSERT INTO public.matches (tournament_id, event_id, phase_group_identifier, round_num, code, advance_match_id, advance_slot_num)
            VALUES (tid, eid, pgid, rnum, 'A', curr_slot.match_id, curr_slot.slot_num)
                RETURNING id
            INTO mid;

            INSERT INTO public.match_slots (tournament_id, event_id, phase_group_identifier, seed_num, match_id, slot_num)
            VALUES (tid, eid, pgid, curr_slot.seed_num, mid, '1'),
                   (tid, eid, pgid, snum, mid, '2');

        END LOOP;


        END IF;
    RETURN;
END;
$function$;

CREATE OR REPLACE FUNCTION public.inc_code(string text)
       RETURNS text
       LANGUAGE plpgsql
       SET search_path TO ''
AS $function$
DECLARE
res text = '';
       carry int = 1;
       ch int;
BEGIN
FOR ch IN
SELECT ascii( unnest( string_to_array(REVERSE(string), NULL) ) )
           LOOP
    IF carry = 1 THEN
            IF ch = 90 THEN
                res := 'A' || res;
ELSE
                res := CHR(ch + 1) || res;
                carry := 0;
END IF;
ELSE
            res := CHR(ch) || res;
END IF;
END LOOP;

    IF carry = 1 THEN
       res := 'A' || res;
END IF;

RETURN res;
END;
$function$;

alter table "public"."bracket_phases" alter column "id" drop identity;

create view bp_detailed as
select bp.*, next.name as next_phase_name, count(*) as num_pools, coalesce(sum(pg.num_seeds), 0) as num_entrants
from public.bracket_phases as bp left outer join public.bracket_phases as next ON (
    bp.tournament_id = next.tournament_id AND bp.event_id = next.event_id AND bp.next_phase_id = next.id
    ) left outer join (
    select phase_groups.tournament_id, phase_groups.event_id, phase_groups.bracket_phase_id, phase_groups.identifier, coalesce(count(*), 0) as num_seeds
    from public.phase_groups inner join public.seeds ON (
    phase_groups.tournament_id = seeds.tournament_id AND phase_groups.event_id = seeds.event_id AND phase_groups.identifier = seeds.phase_group_identifier
    )
    where seeds.entrant_user_id is not null OR seeds.team_name is not null
    group by phase_groups.tournament_id, phase_groups.event_id, phase_groups.identifier
    ) as pg on (bp.tournament_id = pg.tournament_id AND bp.event_id = pg.event_id AND bp.id = pg.bracket_phase_id)
group by bp.tournament_id, bp.event_id, bp.id, next_phase_name;
